# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.IntegerField()),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=200)),
                ('primary_industry', models.CharField(max_length=50)),
                ('num_of_employees', models.IntegerField()),
                ('about_company', models.TextField()),
                ('facebook', models.CharField(max_length=50)),
                ('linkedIn', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('date_established', models.DateField()),
                ('organisation_type', models.CharField(max_length=20)),
                ('tags', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntitySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_info', models.CharField(max_length=15)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('min_qualification', models.CharField(max_length=100)),
                ('min_experience', models.CharField(max_length=100)),
                ('deadline_date', models.DateField()),
                ('score', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('date_created', models.DateField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Applications')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('maiden_name', models.CharField(blank='true', max_length=20)),
                ('gender', models.Field(choices=[('M', 'Male'), ('F', 'Female')])),
                ('birth_date', models.DateField()),
                ('user_type', models.Field(choices=[('Admin', 'Administrator'), ('Recruit', 'Recruiter'), ('seeker', 'Job Seeker')])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('facebook', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('linkedIn', models.CharField(max_length=30)),
                ('score', models.IntegerField()),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.User'),
        ),
        migrations.AddField(
            model_name='profession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.User'),
        ),
        migrations.AddField(
            model_name='job',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Entity'),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Industry'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.JobStatus'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Profession'),
        ),
        migrations.AddField(
            model_name='industry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitysize',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='company_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.EntitySize'),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Country'),
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.User'),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applications',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.User'),
        ),
        migrations.AddField(
            model_name='applications',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.Job'),
        ),
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobonicsapp.ApplicationStage'),
        ),
    ]
